//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Services_Management_App
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Customer.
    /// </summary>
    // *** Start programmer edit section *** (Customer CustomAttributes)

    // *** End programmer edit section *** (Customer CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CustomerE", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Phone as \'Phone\'",
            "EMail as \'E mail\'"})]
    [View("CustomerL", new string[] {
            "Name as \'Name\'",
            "Surname as \'Surname\'",
            "Phone as \'Phone\'",
            "EMail as \'E mail\'"})]
    public class Customer : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fEMail;
        
        private string fSurname;
        
        private string fPhone;
        
        // *** Start programmer edit section *** (Customer CustomMembers)

        // *** End programmer edit section *** (Customer CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Customer.Name CustomAttributes)

        // *** End programmer edit section *** (Customer.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Customer.Name Get start)

                // *** End programmer edit section *** (Customer.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Customer.Name Get end)

                // *** End programmer edit section *** (Customer.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Customer.Name Set start)

                // *** End programmer edit section *** (Customer.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Customer.Name Set end)

                // *** End programmer edit section *** (Customer.Name Set end)
            }
        }
        
        /// <summary>
        /// EMail.
        /// </summary>
        // *** Start programmer edit section *** (Customer.EMail CustomAttributes)

        // *** End programmer edit section *** (Customer.EMail CustomAttributes)
        [StrLen(255)]
        public virtual string EMail
        {
            get
            {
                // *** Start programmer edit section *** (Customer.EMail Get start)

                // *** End programmer edit section *** (Customer.EMail Get start)
                string result = this.fEMail;
                // *** Start programmer edit section *** (Customer.EMail Get end)

                // *** End programmer edit section *** (Customer.EMail Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Customer.EMail Set start)

                // *** End programmer edit section *** (Customer.EMail Set start)
                this.fEMail = value;
                // *** Start programmer edit section *** (Customer.EMail Set end)

                // *** End programmer edit section *** (Customer.EMail Set end)
            }
        }
        
        /// <summary>
        /// Surname.
        /// </summary>
        // *** Start programmer edit section *** (Customer.Surname CustomAttributes)

        // *** End programmer edit section *** (Customer.Surname CustomAttributes)
        [StrLen(255)]
        public virtual string Surname
        {
            get
            {
                // *** Start programmer edit section *** (Customer.Surname Get start)

                // *** End programmer edit section *** (Customer.Surname Get start)
                string result = this.fSurname;
                // *** Start programmer edit section *** (Customer.Surname Get end)

                // *** End programmer edit section *** (Customer.Surname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Customer.Surname Set start)

                // *** End programmer edit section *** (Customer.Surname Set start)
                this.fSurname = value;
                // *** Start programmer edit section *** (Customer.Surname Set end)

                // *** End programmer edit section *** (Customer.Surname Set end)
            }
        }
        
        /// <summary>
        /// Phone.
        /// </summary>
        // *** Start programmer edit section *** (Customer.Phone CustomAttributes)

        // *** End programmer edit section *** (Customer.Phone CustomAttributes)
        [StrLen(255)]
        public virtual string Phone
        {
            get
            {
                // *** Start programmer edit section *** (Customer.Phone Get start)

                // *** End programmer edit section *** (Customer.Phone Get start)
                string result = this.fPhone;
                // *** Start programmer edit section *** (Customer.Phone Get end)

                // *** End programmer edit section *** (Customer.Phone Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Customer.Phone Set start)

                // *** End programmer edit section *** (Customer.Phone Set start)
                this.fPhone = value;
                // *** Start programmer edit section *** (Customer.Phone Set end)

                // *** End programmer edit section *** (Customer.Phone Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CustomerE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CustomerE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CustomerE", typeof(IIS.Services_Management_App.Customer));
                }
            }
            
            /// <summary>
            /// "CustomerL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CustomerL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CustomerL", typeof(IIS.Services_Management_App.Customer));
                }
            }
        }
    }
}
