//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Services_Management_App
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Customer request.
    /// </summary>
    // *** Start programmer edit section *** (CustomerRequest CustomAttributes)

    // *** End programmer edit section *** (CustomerRequest CustomAttributes)
    [AutoAltered()]
    [Caption("Customer request")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CustomerRequestE", new string[] {
            "RequestDate as \'Request date\'",
            "RequestText as \'Request text\'",
            "Customer as \'Customer\'",
            "Customer.Name as \'Name\'"}, Hidden=new string[] {
            "Customer.Name"})]
    [MasterViewDefineAttribute("CustomerRequestE", "Customer", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("CustomerRequestL", new string[] {
            "RequestDate as \'Request date\'",
            "RequestText as \'Request text\'",
            "Customer.Name as \'Name\'"})]
    public class CustomerRequest : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fRequestDate;
        
        private string fRequestText;
        
        private IIS.Services_Management_App.Customer fCustomer;
        
        // *** Start programmer edit section *** (CustomerRequest CustomMembers)

        // *** End programmer edit section *** (CustomerRequest CustomMembers)

        
        /// <summary>
        /// RequestDate.
        /// </summary>
        // *** Start programmer edit section *** (CustomerRequest.RequestDate CustomAttributes)

        // *** End programmer edit section *** (CustomerRequest.RequestDate CustomAttributes)
        public virtual System.DateTime RequestDate
        {
            get
            {
                // *** Start programmer edit section *** (CustomerRequest.RequestDate Get start)

                // *** End programmer edit section *** (CustomerRequest.RequestDate Get start)
                System.DateTime result = this.fRequestDate;
                // *** Start programmer edit section *** (CustomerRequest.RequestDate Get end)

                // *** End programmer edit section *** (CustomerRequest.RequestDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CustomerRequest.RequestDate Set start)

                // *** End programmer edit section *** (CustomerRequest.RequestDate Set start)
                this.fRequestDate = value;
                // *** Start programmer edit section *** (CustomerRequest.RequestDate Set end)

                // *** End programmer edit section *** (CustomerRequest.RequestDate Set end)
            }
        }
        
        /// <summary>
        /// RequestText.
        /// </summary>
        // *** Start programmer edit section *** (CustomerRequest.RequestText CustomAttributes)

        // *** End programmer edit section *** (CustomerRequest.RequestText CustomAttributes)
        [StrLen(255)]
        public virtual string RequestText
        {
            get
            {
                // *** Start programmer edit section *** (CustomerRequest.RequestText Get start)

                // *** End programmer edit section *** (CustomerRequest.RequestText Get start)
                string result = this.fRequestText;
                // *** Start programmer edit section *** (CustomerRequest.RequestText Get end)

                // *** End programmer edit section *** (CustomerRequest.RequestText Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CustomerRequest.RequestText Set start)

                // *** End programmer edit section *** (CustomerRequest.RequestText Set start)
                this.fRequestText = value;
                // *** Start programmer edit section *** (CustomerRequest.RequestText Set end)

                // *** End programmer edit section *** (CustomerRequest.RequestText Set end)
            }
        }
        
        /// <summary>
        /// Customer request.
        /// </summary>
        // *** Start programmer edit section *** (CustomerRequest.Customer CustomAttributes)

        // *** End programmer edit section *** (CustomerRequest.Customer CustomAttributes)
        [NotNull()]
        public virtual IIS.Services_Management_App.Customer Customer
        {
            get
            {
                // *** Start programmer edit section *** (CustomerRequest.Customer Get start)

                // *** End programmer edit section *** (CustomerRequest.Customer Get start)
                IIS.Services_Management_App.Customer result = this.fCustomer;
                // *** Start programmer edit section *** (CustomerRequest.Customer Get end)

                // *** End programmer edit section *** (CustomerRequest.Customer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CustomerRequest.Customer Set start)

                // *** End programmer edit section *** (CustomerRequest.Customer Set start)
                this.fCustomer = value;
                // *** Start programmer edit section *** (CustomerRequest.Customer Set end)

                // *** End programmer edit section *** (CustomerRequest.Customer Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CustomerRequestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CustomerRequestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CustomerRequestE", typeof(IIS.Services_Management_App.CustomerRequest));
                }
            }
            
            /// <summary>
            /// "CustomerRequestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CustomerRequestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CustomerRequestL", typeof(IIS.Services_Management_App.CustomerRequest));
                }
            }
        }
    }
}
