//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Services_Management_App
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Service provider.
    /// </summary>
    // *** Start programmer edit section *** (ServiceProvider CustomAttributes)

    // *** End programmer edit section *** (ServiceProvider CustomAttributes)
    [AutoAltered()]
    [Caption("Service provider")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ServiceProviderE", new string[] {
            "Name as \'Name\'",
            "ContactInfo as \'Contact info\'"})]
    [View("ServiceProviderL", new string[] {
            "Name as \'Name\'",
            "ContactInfo as \'Contact info\'"})]
    public class ServiceProvider : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fContactInfo;
        
        // *** Start programmer edit section *** (ServiceProvider CustomMembers)

        // *** End programmer edit section *** (ServiceProvider CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ServiceProvider.Name CustomAttributes)

        // *** End programmer edit section *** (ServiceProvider.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ServiceProvider.Name Get start)

                // *** End programmer edit section *** (ServiceProvider.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ServiceProvider.Name Get end)

                // *** End programmer edit section *** (ServiceProvider.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceProvider.Name Set start)

                // *** End programmer edit section *** (ServiceProvider.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ServiceProvider.Name Set end)

                // *** End programmer edit section *** (ServiceProvider.Name Set end)
            }
        }
        
        /// <summary>
        /// ContactInfo.
        /// </summary>
        // *** Start programmer edit section *** (ServiceProvider.ContactInfo CustomAttributes)

        // *** End programmer edit section *** (ServiceProvider.ContactInfo CustomAttributes)
        [StrLen(255)]
        public virtual string ContactInfo
        {
            get
            {
                // *** Start programmer edit section *** (ServiceProvider.ContactInfo Get start)

                // *** End programmer edit section *** (ServiceProvider.ContactInfo Get start)
                string result = this.fContactInfo;
                // *** Start programmer edit section *** (ServiceProvider.ContactInfo Get end)

                // *** End programmer edit section *** (ServiceProvider.ContactInfo Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ServiceProvider.ContactInfo Set start)

                // *** End programmer edit section *** (ServiceProvider.ContactInfo Set start)
                this.fContactInfo = value;
                // *** Start programmer edit section *** (ServiceProvider.ContactInfo Set end)

                // *** End programmer edit section *** (ServiceProvider.ContactInfo Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ServiceProviderE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ServiceProviderE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ServiceProviderE", typeof(IIS.Services_Management_App.ServiceProvider));
                }
            }
            
            /// <summary>
            /// "ServiceProviderL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ServiceProviderL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ServiceProviderL", typeof(IIS.Services_Management_App.ServiceProvider));
                }
            }
        }
    }
}
