//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Services_Management_App
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// T event type.
    /// </summary>
    // *** Start programmer edit section *** (tEventType CustomAttributes)

    // *** End programmer edit section *** (tEventType CustomAttributes)
    public enum tEventType
    {
        
        // *** Start programmer edit section *** (tEventType.Movie CustomAttributes)

        // *** End programmer edit section *** (tEventType.Movie CustomAttributes)
        Movie,
        
        // *** Start programmer edit section *** (tEventType.Concert CustomAttributes)

        // *** End programmer edit section *** (tEventType.Concert CustomAttributes)
        Concert,
        
        // *** Start programmer edit section *** (tEventType.Performance CustomAttributes)

        // *** End programmer edit section *** (tEventType.Performance CustomAttributes)
        Performance,
    }
}
